/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CountListListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheCountListListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheCountListListGenerated.onFilterBar().iCheckFilterField("Physical Inventory Document");
            Then.onTheCountListListGenerated.onFilterBar().iCheckFilterField("Fiscal Year");
            Then.onTheCountListListGenerated.onFilterBar().iCheckFilterField("Plant");
            Then.onTheCountListListGenerated.onFilterBar().iCheckFilterField("Storage Location");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheCountListListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheCountListListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheCountListListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheCountListListGenerated.onTable().iCheckColumns(undefined, {"PhysicalInventoryDocument":{"header":"Physical Inventory Document"},"FiscalYear":{"header":"Fiscal Year"},"Plant":{"header":"Plant"},"StorageLocation":{"header":"Storage Location"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheCountListListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheCountListListGenerated.onTable().iCheckRows();

            When.onTheCountListListGenerated.onTable().iPressRow(0);
            Then.onTheCountListObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});