/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CountListObjectPageObjectPage journey");

        opaTest("Navigate to CountListObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheCountListListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheCountListListGenerated.onTable().iCheckRows();
            When.onTheCountListListGenerated.onTable().iPressRow(0);

            Then.onTheCountListObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheCountListObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "FieldGroup::HeaderData" });
            Then.onTheCountListObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "HeaderData",
                field: "PhysicalInventoryDocument",
                targetAnnotation: ""
            });
            Then.onTheCountListObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "HeaderData",
                field: "FiscalYear",
                targetAnnotation: ""
            });
            Then.onTheCountListObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "HeaderData",
                field: "Plant",
                targetAnnotation: ""
            });
            Then.onTheCountListObjectPageGenerated.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "HeaderData",
                field: "StorageLocation",
                targetAnnotation: ""
            });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheCountListObjectPageGenerated.iCheckSection({ section: "Item" });
            Then.onTheCountListObjectPageGenerated.onTable({ property: "_CountListItem" }).iCheckColumns(undefined, {"PhysicalInventoryDocumentItem":{"header":"Item"},"Material":{"header":"Material"},"AvailableQuantity":{"header":"Available Quantity"},"ItemPrice":{"header":"Item Price"},"TotalAmount":{"header":"Total Amount"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});